FROM opensuse:13.2

RUN (cd /usr/lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /usr/lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /usr/lib/systemd/system/local-fs.target.wants/*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /usr/lib/systemd/system/basic.target.wants/*;

# Add ansible 2.0 repo
RUN zypper  --no-gpg-checks --gpg-auto-import-keys addrepo http://download.opensuse.org/repositories/systemsmanagement/openSUSE_13.2/ systemsmanagement

# Install Ansible
RUN zypper --gpg-auto-import-keys --non-interactive install git ansible sudo

# Install Ansible inventory file
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/sbin/init"]
